galaxy_info:
  author: Ben Dews
  description: Ansible Container Flask Demo
  company: bendews.com
  license: MIT

  min_ansible_container_version: 0.9.2

  galaxy_tags:
  - container
  - nginx
  - flask
  - redis
  - demo
  - hello
  - world
